echo " ==   Run Statistics for LS started at @ `date`  ==\n"

. /home/db2inst1/sqllib/db2profile

db2 connect to icmnlsdb user icmadmin using cmlsdev

db2 runstats on table ICMADMIN.BROKER with distribution and detailed indexes all
db2 runstats on table ICMADMIN.BROKERADM with distribution and detailed indexes all
db2 runstats on table ICMADMIN.BROKERADMSB with distribution and detailed indexes all
db2 runstats on table ICMADMIN.CARRIERCODE with distribution and detailed indexes all
db2 runstats on table ICMADMIN.CLIENT with distribution and detailed indexes all
db2 runstats on table ICMADMIN.CLIENTADM with distribution and detailed indexes all
db2 runstats on table ICMADMIN.EPICTBROKER with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FAASSOCSERV with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FACC2MIME with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FADEFAULTVALUES with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FAFEDATTRIBUTE with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FAFEDATTRMAP with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FAFEDENTITY with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FAFEDFOLDER with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FAFEDFOLDERMAP with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FAFEDPART with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FAGROUPTEMPLATE with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FAINVENTORY with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FALOG with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FAMIME2APP with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FANATIVEENTITYATTR with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FANLSLANGUAGE with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FANLSWORD with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FAOPTIONS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FAPARAMETRICFIELD with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FAPREDEFINEDVALUES with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FASERVERS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FASERVERTYPES with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FATEMPLATE with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FATEXTFIELD with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FATEXTINVENTORY with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FATEXTINVENTORYNLS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FATEXTMAP with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FATEXTNATIVEENT with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FAUSERMAP with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FAVALIDOPS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.FTP_CLIENT with distribution and detailed indexes all
db2 runstats on table ICMADMIN.GATEWAY with distribution and detailed indexes all
db2 runstats on table ICMADMIN.GATEWAY_PORT_MAP with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTACCESSCODES with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTACCESSLISTS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTACTIONLISTCD with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTACTIONLISTS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTACTIONLISTSCM with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTACTIONS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTACTIONSCM with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTADMINDOMAINS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTALISTCDCM with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTATTRDEFS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTATTRGROUP with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTCHECKEDOUT with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTCOLLECTIONPT with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTCOLLNAME with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTCOMPATTRS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTCOMPATTRSFK with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTCOMPDEFS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTCOMPILEDACL with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTCOMPILEDPERM with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTCOMPVIEWATTRS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTCOMPVIEWDEFS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTDIAGPROMPT with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTDIAGRAMS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTDOMAINACCESS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTDOMAINPRIVSET with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTEVENTQUEUE with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTEVENTSUBSCRIPTIONATTRS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTEVENTSUBSCRIPTIONS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTIIDTORID with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTITEMAUTOLINK with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTITEMEVENTS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTITEMS001001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTITEMSTODELETE with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTITEMTYPEDEFS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTITEMTYPEREL with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTITEMVER001001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTITVIEWDEFS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTITVIEWID with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTLINKS001001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTLSUPDATEHIST with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTMAXKEYWORD with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTMIMETYPES with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTNLSKEYWORDS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTNLSLANGUAGES with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTPRIVDEFS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTPRIVGROUPCODE with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTPRIVGROUPS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTPRIVSETCODES with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTPRIVSETS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTREPLICARULES with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTREPLICAS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTRESOURCEMGR with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTRI001001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTRMACCESSTYPES with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTSYSADMEVENTS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTSYSCONTROL with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTTEXTINDEXCONF with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTTIELOG with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTUSERGROUPS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTUSERS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTVIEWACCESS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTWORKFLOWEVENT with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTWORKLISTS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTXDOOBJECTS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMSTXDOOBJFACTORY with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT00200001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT00201001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT00202001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT00203001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT00204001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT00205001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT00206001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT00207001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT00208001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT00209001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT00210001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT00300001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT00301001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT00302001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT00303001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT00304001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT00400001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01000001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01001001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01002001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01003001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01004001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01005001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01006001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01880001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01881001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01882001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01883001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01884001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01885001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01886001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01887001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01888001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01889001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01890001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01891001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01892001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01893001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01894001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01895001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01896001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01897001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01898001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01899001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01900001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01901001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01902001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01903001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01904001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01905001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01906001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01907001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01908001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01909001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01910001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01911001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01912001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01913001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01914001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01915001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01916001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01917001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01918001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01919001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01920001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01921001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01922001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01923001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01924001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01925001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01926001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01927001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01928001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01929001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01930001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01931001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01932001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01933001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01934001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01935001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01936001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01937001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01938001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01939001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01940001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01941001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01942001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01943001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01944001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01945001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01946001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01947001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01948001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01949001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01950001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01951001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01952001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01953001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01954001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01955001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01956001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01957001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01958001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01959001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01960001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01961001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01962001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01963001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01964001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01965001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01966001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01967001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01968001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01969001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01970001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01971001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01972001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01973001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01974001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01975001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01976001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01977001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01978001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01979001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01980001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01981001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01982001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01983001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01984001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01985001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01986001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01987001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01988001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01989001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01990001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01991001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01992001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01993001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01994001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01995001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01996001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01997001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01998001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT01999001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02000001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02001001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02002001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02003001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02004001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02005001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02006001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02007001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02008001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02009001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02010001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02011001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02012001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02013001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02014001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02015001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02016001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02017001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02018001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02019001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02020001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02021001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02022001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02023001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02024001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02025001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02026001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02027001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02028001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02029001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02030001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02031001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02032001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02033001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02034001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02035001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02036001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02037001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02038001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02039001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02040001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02041001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02042001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02043001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02044001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02045001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02046001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02047001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02048001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02049001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02050001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02051001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02052001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02053001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02054001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02055001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02056001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02057001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02058001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02059001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02060001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02061001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02062001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02063001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02064001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02065001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02066001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02067001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02068001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02069001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02070001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02071001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02072001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02073001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02074001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02075001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02076001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02077001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02078001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02079001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02080001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02097001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02098001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02099001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02100001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02121001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02122001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02123001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02124001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02133001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02134001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02190001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02191001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02192001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02193001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02194001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02195001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02196001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02197001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02198001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02199001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02200001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02201001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02202001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02203001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02204001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02205001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02206001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02207001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02208001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02209001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02210001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02211001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02212001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02213001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02218001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.ICMUT02219001 with distribution and detailed indexes all
db2 runstats on table ICMADMIN.PORTS with distribution and detailed indexes all
db2 runstats on table ICMADMIN.RMEAUDIT with distribution and detailed indexes all
db2 runstats on table ICMADMIN.RMEAUTODECLARE with distribution and detailed indexes all
db2 runstats on table ICMADMIN.UPESCP with distribution and detailed indexes all
db2 runstats on table ICMADMIN.UPESCPBRANCH with distribution and detailed indexes all
db2 runstats on table ICMADMIN.UPESCPCONTAINER with distribution and detailed indexes all
db2 runstats on table ICMADMIN.XREFCLIENTBROKERADM with distribution and detailed indexes all

db2 connect reset

echo "\n== Run Statistics for LS completed @ `date`==\n\n"

echo "** Run binding for LS started @ `date` ** \n"

db2rbind icmnlsdb -l /home/db2inst1/mgmt/db2stats/ls_stats.log all -u icmadmin -p cmlsdev

echo "** Run binding for LS finished @ `date` ** \n"

