. /home/db2inst1/sqllib/db2profile
date
db2 connect to icmnlsdb
print "start Reorgchk ..."
db2 reorgchk current statistics on table icmadmin.BROKER                                                                                                                          
db2 reorgchk current statistics on table icmadmin.BROKERADM                                                                                                                       
db2 reorgchk current statistics on table icmadmin.CLIENT                                                                                                                          
db2 reorgchk current statistics on table icmadmin.CLIENTADM                                                                                                                       
db2 reorgchk current statistics on table icmadmin.EPICTBROKER                                                                                                                     
db2 reorgchk current statistics on table icmadmin.FAASSOCSERV                                                                                                                     
db2 reorgchk current statistics on table icmadmin.FACC2MIME                                                                                                                       
db2 reorgchk current statistics on table icmadmin.FADEFAULTVALUES                                                                                                                 
db2 reorgchk current statistics on table icmadmin.FAFEDATTRIBUTE                                                                                                                  
db2 reorgchk current statistics on table icmadmin.FAFEDATTRMAP                                                                                                                    
db2 reorgchk current statistics on table icmadmin.FAFEDENTITY                                                                                                                     
db2 reorgchk current statistics on table icmadmin.FAFEDFOLDER                                                                                                                     
db2 reorgchk current statistics on table icmadmin.FAFEDFOLDERMAP                                                                                                                  
db2 reorgchk current statistics on table icmadmin.FAFEDPART                                                                                                                       
db2 reorgchk current statistics on table icmadmin.FAGROUPTEMPLATE                                                                                                                 
db2 reorgchk current statistics on table icmadmin.FAINVENTORY                                                                                                                     
db2 reorgchk current statistics on table icmadmin.FALOG                                                                                                                           
db2 reorgchk current statistics on table icmadmin.FAMIME2APP                                                                                                                      
db2 reorgchk current statistics on table icmadmin.FANATIVEENTITYATTR                                                                                                              
db2 reorgchk current statistics on table icmadmin.FANLSLANGUAGE                                                                                                                   
db2 reorgchk current statistics on table icmadmin.FANLSWORD                                                                                                                       
db2 reorgchk current statistics on table icmadmin.FAOPTIONS                                                                                                                       
db2 reorgchk current statistics on table icmadmin.FAPARAMETRICFIELD                                                                                                               
db2 reorgchk current statistics on table icmadmin.FAPREDEFINEDVALUES                                                                                                              
db2 reorgchk current statistics on table icmadmin.FASERVERS                                                                                                                       
db2 reorgchk current statistics on table icmadmin.FASERVERTYPES                                                                                                                   
db2 reorgchk current statistics on table icmadmin.FATEMPLATE                                                                                                                      
db2 reorgchk current statistics on table icmadmin.FATEXTFIELD                                                                                                                     
db2 reorgchk current statistics on table icmadmin.FATEXTINVENTORY                                                                                                                 
db2 reorgchk current statistics on table icmadmin.FATEXTINVENTORYNLS                                                                                                              
db2 reorgchk current statistics on table icmadmin.FATEXTMAP                                                                                                                       
db2 reorgchk current statistics on table icmadmin.FATEXTNATIVEENT                                                                                                                 
db2 reorgchk current statistics on table icmadmin.FAUSERMAP                                                                                                                       
db2 reorgchk current statistics on table icmadmin.FAVALIDOPS                                                                                                                      
db2 reorgchk current statistics on table icmadmin.GATEWAY                                                                                                                         
db2 reorgchk current statistics on table icmadmin.GATEWAY_PORT_MAP                                                                                                                
db2 reorgchk current statistics on table icmadmin.ICMSTACCESSCODES                                                                                                                
db2 reorgchk current statistics on table icmadmin.ICMSTACCESSLISTS                                                                                                                
db2 reorgchk current statistics on table icmadmin.ICMSTACTIONLISTCD                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTACTIONLISTS                                                                                                                
db2 reorgchk current statistics on table icmadmin.ICMSTACTIONLISTSCM                                                                                                              
db2 reorgchk current statistics on table icmadmin.ICMSTACTIONS                                                                                                                    
db2 reorgchk current statistics on table icmadmin.ICMSTACTIONSCM                                                                                                                  
db2 reorgchk current statistics on table icmadmin.ICMSTADMINDOMAINS                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTALISTCDCM                                                                                                                  
db2 reorgchk current statistics on table icmadmin.ICMSTATTRDEFS                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMSTATTRGROUP                                                                                                                  
db2 reorgchk current statistics on table icmadmin.ICMSTCHECKEDOUT                                                                                                                 
db2 reorgchk current statistics on table icmadmin.ICMSTCOLLECTIONPT                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTCOLLNAME                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMSTCOMPATTRS                                                                                                                  
db2 reorgchk current statistics on table icmadmin.ICMSTCOMPATTRSFK                                                                                                                
db2 reorgchk current statistics on table icmadmin.ICMSTCOMPDEFS                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMSTCOMPILEDACL                                                                                                                
db2 reorgchk current statistics on table icmadmin.ICMSTCOMPILEDPERM                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTCOMPVIEWATTRS                                                                                                              
db2 reorgchk current statistics on table icmadmin.ICMSTCOMPVIEWDEFS                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTDIAGPROMPT                                                                                                                 
db2 reorgchk current statistics on table icmadmin.ICMSTDIAGRAMS                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMSTDOMAINACCESS                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTDOMAINPRIVSET                                                                                                              
db2 reorgchk current statistics on table icmadmin.ICMSTITEMAUTOLINK                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTITEMEVENTS                                                                                                                 
db2 reorgchk current statistics on table icmadmin.ICMSTITEMS001001                                                                                                                
db2 reorgchk current statistics on table icmadmin.ICMSTITEMSTODELETE                                                                                                              
db2 reorgchk current statistics on table icmadmin.ICMSTITEMTYPEDEFS                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTITEMTYPEREL                                                                                                                
db2 reorgchk current statistics on table icmadmin.ICMSTITEMVER001001                                                                                                              
db2 reorgchk current statistics on table icmadmin.ICMSTITVIEWDEFS                                                                                                                 
db2 reorgchk current statistics on table icmadmin.ICMSTITVIEWID                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMSTJCRADDTLPROPS                                                                                                              
db2 reorgchk current statistics on table icmadmin.ICMSTJCRDELTALINKS                                                                                                              
db2 reorgchk current statistics on table icmadmin.ICMSTJCRDUMMY                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMSTJCRGENDDL                                                                                                                  
db2 reorgchk current statistics on table icmadmin.ICMSTJCRGLBLPROPS                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTJCRIDS                                                                                                                     
db2 reorgchk current statistics on table icmadmin.ICMSTJCRLINKS                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMSTJCRMAXSNSIDX                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTJCRNODEDEFS                                                                                                                
db2 reorgchk current statistics on table icmadmin.ICMSTJCRNODELOCKS                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTJCRNODETYPES                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTJCRNSPREFIXES                                                                                                              
db2 reorgchk current statistics on table icmadmin.ICMSTJCRNSURIS                                                                                                                  
db2 reorgchk current statistics on table icmadmin.ICMSTJCRPROPDEFS                                                                                                                
db2 reorgchk current statistics on table icmadmin.ICMSTJCRRNODETYPES                                                                                                              
db2 reorgchk current statistics on table icmadmin.ICMSTJCRROOT                                                                                                                    
db2 reorgchk current statistics on table icmadmin.ICMSTJCRSUPERTYPES                                                                                                              
db2 reorgchk current statistics on table icmadmin.ICMSTJCRTIMESTAMPS                                                                                                              
db2 reorgchk current statistics on table icmadmin.ICMSTJCRTSERRORS                                                                                                                
db2 reorgchk current statistics on table icmadmin.ICMSTJCRTSINDEXES                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTJCRTSPENDING                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTJCRTSTABLES                                                                                                                
db2 reorgchk current statistics on table icmadmin.ICMSTJCRWS                                                                                                                      
db2 reorgchk current statistics on table icmadmin.ICMSTJCRWSNODES                                                                                                                 
db2 reorgchk current statistics on table icmadmin.ICMSTLINKS001001                                                                                                                
db2 reorgchk current statistics on table icmadmin.ICMSTLSUPDATEHIST                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTMAXKEYWORD                                                                                                                 
db2 reorgchk current statistics on table icmadmin.ICMSTMIMETYPES                                                                                                                  
db2 reorgchk current statistics on table icmadmin.ICMSTNLSKEYWORDS                                                                                                                
db2 reorgchk current statistics on table icmadmin.ICMSTNLSLANGUAGES                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTPRIVDEFS                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMSTPRIVGROUPCODE                                                                                                              
db2 reorgchk current statistics on table icmadmin.ICMSTPRIVGROUPS                                                                                                                 
db2 reorgchk current statistics on table icmadmin.ICMSTPRIVSETCODES                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTPRIVSETS                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMSTREPLICARULES                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTREPLICAS                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMSTRESOURCEMGR                                                                                                                
db2 reorgchk current statistics on table icmadmin.ICMSTRI001001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMSTRMACCESSTYPES                                                                                                              
db2 reorgchk current statistics on table icmadmin.ICMSTSYSADMEVENTS                                                                                                               
db2 reorgchk current statistics on table icmadmin.ICMSTSYSCONTROL                                                                                                                 
db2 reorgchk current statistics on table icmadmin.ICMSTTEXTINDEXCONF                                                                                                              
db2 reorgchk current statistics on table icmadmin.ICMSTTIELOG                                                                                                                     
db2 reorgchk current statistics on table icmadmin.ICMSTUSERGROUPS                                                                                                                 
db2 reorgchk current statistics on table icmadmin.ICMSTUSERS                                                                                                                      
db2 reorgchk current statistics on table icmadmin.ICMSTVIEWACCESS                                                                                                                 
db2 reorgchk current statistics on table icmadmin.ICMSTWORKFLOWEVENT                                                                                                              
db2 reorgchk current statistics on table icmadmin.ICMSTWORKLISTS                                                                                                                  
db2 reorgchk current statistics on table icmadmin.ICMSTXDOOBJECTS                                                                                                                 
db2 reorgchk current statistics on table icmadmin.ICMSTXDOOBJFACTORY                                                                                                              
db2 reorgchk current statistics on table icmadmin.ICMUT00200001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT00201001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT00202001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT00203001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT00204001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT00205001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT00206001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT00207001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT00208001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT00209001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT00210001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT00300001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT00301001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT00302001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT00303001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT00304001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT00400001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT00600001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01000001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01001001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01002001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01003001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01004001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01005001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01006001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01007001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01008001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01057001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01058001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01059001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01060001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01061001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01062001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01063001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01064001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01065001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01066001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01067001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01068001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01069001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01070001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01071001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01072001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01073001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01074001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01075001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01233001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01235001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01237001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01255001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01256001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01257001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01284001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01285001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01286001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01287001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01288001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01289001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01290001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01291001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01292001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01293001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01294001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01295001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01312001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01313001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01318001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01319001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01320001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01321001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01322001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01323001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01324001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01325001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01326001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01327001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01328001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01329001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01330001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01331001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01332001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01333001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01334001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01335001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01336001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01337001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01338001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01339001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01340001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01341001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01342001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01343001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01514001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01515001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01518001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01519001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01522001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01523001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01526001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01527001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01534001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01535001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01540001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01541001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01602001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01603001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01606001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01607001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01618001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01619001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01622001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01623001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01628001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01629001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01632001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01633001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01636001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01637001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01640001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01641001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01644001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01645001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01648001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01649001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01652001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01653001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01656001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01657001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01664001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01665001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01668001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01669001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01672001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01673001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01676001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01677001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01678001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01679001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01680001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01681001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01682001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01683001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01684001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01685001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01686001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01687001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01688001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01689001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01690001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.ICMUT01691001                                                                                                                   
db2 reorgchk current statistics on table icmadmin.PORTS                                                                                                                           
db2 reorgchk current statistics on table icmadmin.UPESCP                                                                                                                          
db2 reorgchk current statistics on table icmadmin.UPESCPBRANCH                                                                                                                    
db2 reorgchk current statistics on table icmadmin.UPESCPCONTAINER                                                                                                                 
db2 reorgchk current statistics on table icmadmin.XREFCLIENTBROKERADM                                                                                                             
db2 connect reset
date
print "Completed!! "
